name: basics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  core:
    uses: runziggurat/ziggurat-core/.github/workflows/check-and-lint.yml@main

  extra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        steps:
          - name: test
            run: cargo test -- --test-threads=1 --ignored
          - name: check-crawler
            run: cargo check --features=crawler
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: ${{ matrix.steps.name }}
        run: |
          nix develop --command \
          ${{ matrix.steps.run }}
