on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  process-results:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ inputs.name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: latest-result
          path: results/$NAME/latest.jsonl
      - name: Process results
        run: |
          FILENAME=$(date +%Y-%m-%d)
          cd results/$NAME
          cp latest.jsonl $FILENAME.jsonl
          gzip $FILENAME.jsonl
      - name: Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add results/$NAME
          git commit -m "ci: $NAME suite results"
          git push
