name: zcashd-nightly

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 6:00 AM UTC.

jobs:
  install-zcashd:
    runs-on: ubuntu-latest
    steps:
      - name: clone zcashd
        run: git clone https://github.com/zcash/zcash
      - name: build zcashd
        run: |
          cd zcash
          ./zcutil/build.sh -j$(nproc)
      - uses: actions/upload-artifact@v3
        with:
          name: zcashd-fetch-params
          path: ./zcash/zcutil/fetch-params.sh
      - uses: actions/upload-artifact@v3
        with:
          name: zcashd-executable
          path: ./zcash/src/zcashd

  install-ziggurat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Compile unit tests
        run: cargo test --all-targets --no-run
      - uses: actions/upload-artifact@v3
        with:
          name: ziggurat-executable
          path: ./target/debug/deps/ziggurat-*

  test-zcashd:
    runs-on: ubuntu-latest
    needs: [ install-ziggurat, install-zcashd ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: rustup toolchain install nightly --profile minimal
      - uses: actions/download-artifact@v3
        with:
          name: zcashd-fetch-params
          path: ./zcash
      - uses: actions/download-artifact@v3
        with:
          name: zcashd-executable
          path: ./zcash
      - uses: actions/download-artifact@v3
        with:
          name: ziggurat-executable
          path: ./ziggurat
      - name: Create ~/.ziggurat/config.toml
        run: |
          mkdir ~/.ziggurat/
          touch ~/.ziggurat/config.toml
          echo kind = \"zcashd\" > ~/.ziggurat/config.toml
          echo path = \"/home/runner/work/zcash/zcash/zcash\" >> ~/.ziggurat/config.toml
          echo start_command = \"./zcashd -debug=1 -printtoconsole -logips=1 -dnsseed=0 -dns=0 -listenonion=0\" >> ~/.ziggurat/config.toml
      - name: Fetch zcashd params
        run: |
          chmod +x zcash/fetch-params.sh
          ./zcash/fetch-params.sh
      - name: Run ziggurat suite
        continue-on-error: true
        run: |
          rm ./ziggurat/*.d
          mv ./ziggurat/ziggurat-* ziggurat_test
          chmod +x ziggurat_test
          chmod +x zcash/zcashd
          mkdir -p results/zcashd
          mv results/zcashd/latest.jsonl results/zcashd/comparison.jsonl
          ./ziggurat_test --test-threads=1 --nocapture -Z unstable-options --report-time --format json > results/zcashd/latest.jsonl
          cat results/zcashd/latest.jsonl
      - name: Process results
        run: |
          FILENAME=$(date +%Y-%m-%d)
          cd results/zcashd
          cp latest.jsonl $FILENAME.jsonl
          gzip $FILENAME.jsonl
      - name: Compare results
        run: |
          # Helper function to remove ignored tests and started ones, and then attributes exec_time and type
          filter_json() {
            tmp=$(mktemp)
            ! jq 'del(select(.event == "ignored"))' $1 > $tmp && mv $tmp $1 # Remove ignored tests
            jq 'del(select(.event == "started"))' $1 > $tmp && mv $tmp $1 # Remove started tests
            jq 'del(.exec_time) | del(.type)' $1 > $tmp && mv $tmp $1 # Remove exec_time and type attributes
            # Remove null characters and empty lines
            sed -i 's/null//g' $1
            sed -i '/^$/d' $1
          }
          mkdir temp
          cp results/zcashd/latest.jsonl temp/
          mv results/zcashd/comparison.jsonl temp/
          cd temp
          filter_json latest.jsonl
          filter_json comparison.jsonl
          ! diff -u comparison.jsonl latest.jsonl
          cd ..
          rm -rf temp
      - name: Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add results/zcashd
          git commit -m "ci: zcashd suite results"
          git push
