name: zebra

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 6:00 AM UTC.

jobs:
  build-zebra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ZcashFoundation/zebra
      - run: rustup toolchain install stable --profile minimal
      - name: build Zebra and download artifacts
        run: cargo +stable build --release
      - uses: actions/upload-artifact@v3
        with:
          name: zebra-executable
          path: ./target/release/zebrad

  build-ziggurat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Compile unit tests
        run: cargo test --all-targets --no-run
      - uses: actions/upload-artifact@v3
        with:
          name: ziggurat-executable
          path: ./target/debug/deps/ziggurat-*

  test-zebra:
    runs-on: ubuntu-latest
    needs: [ build-zebra, build-ziggurat ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: rustup toolchain install nightly --profile minimal
      - uses: actions/download-artifact@v3
        with:
          name: zebra-executable
          path: ./zebrad
      - uses: actions/download-artifact@v3
        with:
          name: ziggurat-executable
          path: ./ziggurat
      - run: |
          chmod +x ./zebrad/zebrad
      - name: Create ~/.ziggurat/config.toml
        run: |
          mkdir ~/.ziggurat/
          touch ~/.ziggurat/config.toml
          echo kind = \"zebra\" > ~/.ziggurat/config.toml
          echo path = \"/home/runner/work/zcash/zcash/zebrad\" >> ~/.ziggurat/config.toml
          echo start_command = \"./zebrad start\" >> ~/.ziggurat/config.toml
      - name: Run ziggurat suite
        continue-on-error: true
        run: |
          rm ./ziggurat/*.d
          mv ./ziggurat/ziggurat-* ziggurat_test
          chmod +x ziggurat_test
          mkdir -p results/zebra
          mv results/zebra/latest.jsonl results/zebra/comparison.jsonl
          ./ziggurat_test --test-threads=1 --nocapture -Z unstable-options --report-time --format json > results/zebra/latest.jsonl
          cat results/zebra/latest.jsonl
      - name: Process results
        run: |
          FILENAME=$(date +%Y-%m-%d)
          cd results/zebra
          cp latest.jsonl $FILENAME.jsonl
          gzip $FILENAME.jsonl
      - name: Compare results
        run: |
          # Helper function to remove ignored tests and started ones, and then attributes exec_time and type
          filter_json() {
            tmp=$(mktemp)
            ! jq 'del(select(.event == "ignored"))' $1 > $tmp && mv $tmp $1 # Remove ignored tests
            jq 'del(select(.event == "started"))' $1 > $tmp && mv $tmp $1 # Remove started tests
            jq 'del(.exec_time) | del(.type)' $1 > $tmp && mv $tmp $1 # Remove exec_time and type attributes
            # Remove null characters and empty lines
            sed -i 's/null//g' $1
            sed -i '/^$/d' $1
          }
          mkdir temp
          cp results/zebra/latest.jsonl temp/
          mv results/zebra/comparison.jsonl temp/
          cd temp
          filter_json latest.jsonl
          filter_json comparison.jsonl
          ! diff -u comparison.jsonl latest.jsonl
          cd ..
          rm -rf temp
      - name: Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add results/zebra
          git commit -m "ci: zebra suite results"
          git push
